// ==========================================================================================
//  GameFrameX 组织及其衍生项目的版权、商标、专利及其他相关权利
//  GameFrameX organization and its derivative projects' copyrights, trademarks, patents, and related rights
//  均受中华人民共和国及相关国际法律法规保护。
//  are protected by the laws of the People's Republic of China and relevant international regulations.
//
//  使用本项目须严格遵守相应法律法规及开源许可证之规定。
//  Usage of this project must strictly comply with applicable laws, regulations, and open-source licenses.
//
//  本项目采用 MIT 许可证与 Apache License 2.0 双许可证分发，
//  This project is dual-licensed under the MIT License and Apache License 2.0,
//  完整许可证文本请参见源代码根目录下的 LICENSE 文件。
//  please refer to the LICENSE file in the root directory of the source code for the full license text.
//
//  禁止利用本项目实施任何危害国家安全、破坏社会秩序、
//  It is prohibited to use this project to engage in any activities that endanger national security, disrupt social order,
//  侵犯他人合法权益等法律法规所禁止的行为！
//  or infringe upon the legitimate rights and interests of others, as prohibited by laws and regulations!
//  因基于本项目二次开发所产生的一切法律纠纷与责任，
//  Any legal disputes and liabilities arising from secondary development based on this project
//  本项目组织与贡献者概不承担。
//  shall be borne solely by the developer; the project organization and contributors assume no responsibility.
//
//  GitHub 仓库：https://github.com/GameFrameX
//  GitHub Repository: https://github.com/GameFrameX
//  Gitee  仓库：https://gitee.com/GameFrameX
//  Gitee Repository:  https://gitee.com/GameFrameX
//  CNB  仓库：https://cnb.cool/GameFrameX
//  CNB Repository:  https://cnb.cool/GameFrameX
//  官方文档：https://gameframex.doc.alianblank.com/
//  Official Documentation: https://gameframex.doc.alianblank.com/
// ==========================================================================================

using GameFrameX.Foundation.Json;
using Serilog;
using Serilog.Events;

namespace GameFrameX.Foundation.Logger;

/// <summary>
/// 日志配置类，用于配置日志的相关选项。
/// </summary>
/// <remarks>
/// This class provides a series of log-related configuration options, including log storage path, output level, file size limit, etc.
/// Through these configurations, you can flexibly control the output behavior and storage method of logs.
/// </remarks>
public sealed class LogOptions
{
    /// <summary>
    /// 默认构造函数，初始化日志配置对象。
    /// </summary>
    /// <param name="logPathName">日志存储路径名称 / The log storage path name</param>
    public LogOptions(string logPathName = "logs")
    {
        if (string.IsNullOrWhiteSpace(logPathName))
        {
            logPathName = "logs";
        }

        LogSavePath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "data", logPathName);
    }

    /// <summary>
    /// 默认配置对象，提供一个默认的日志配置实例。
    /// </summary>
    /// <remarks>
    /// Use this static instance to quickly get a log configuration object with default settings.
    /// </remarks>
    public static readonly LogOptions Default = new();

    /// <summary>
    /// 是否写入文件，默认为 true。 / Whether to write to file, default is true.
    /// </summary>
    public bool IsWriteToFile { get; set; } = true;

    /// <summary>
    /// 服务器类型，用于标识日志来源的服务器类型。 / Server type, used to identify the server type of log source.
    /// </summary>
    /// <remarks>
    /// Can be used to distinguish logs generated by different servers for log classification and management.
    /// </remarks>
    public string LogType { get; set; }

    /// <summary>
    /// 日志标签名，用于标识日志的名称或描述。 / Log tag name, used to identify the log name or description.
    /// </summary>
    /// <remarks>
    /// Can be used to distinguish logs generated by different servers for log classification and management.
    /// </remarks>
    public string LogTagName { get; set; } = "";

    /// <summary>
    /// 是否写入数据库，默认为 false。 / Whether to write to database, default is false.
    /// </summary>
    public bool IsWriteToMongoDb { get; set; } = false;

    /// <summary>
    /// MongoDB 数据库连接地址，用于保存日志数据 / MongoDB database connection URL for saving log data
    /// </summary>
    /// <remarks>
    /// <para>
    /// When <see cref="IsWriteToMongoDb"/> is set to true, this property must be configured with a valid MongoDB connection string.
    /// The connection string should include database server address, port, database name, and authentication information.
    /// </para>
    /// <para>
    /// Connection string format: mongodb://[username:password@]host[:port]/database[?options]
    /// </para>
    /// <para>
    /// Common configuration examples:
    /// <list type="bullet">
    /// <item><description>Local without authentication: mongodb://localhost:27017/gameserver</description></item>
    /// <item><description>Local with authentication: mongodb://user:password@localhost:27017/gameserver?authSource=admin</description></item>
    /// <item><description>Remote server: mongodb://user:password@192.168.1.100:27017/gameserver?authSource=admin</description></item>
    /// <item><description>Replica set: mongodb://user:password@host1:27017,host2:27017/gameserver?replicaSet=rs0&amp;authSource=admin</description></item>
    /// </list>
    /// </para>
    /// <para>
    /// Note: Ensure the MongoDB server is started and the network connection is normal, otherwise log writing will fail.
    /// </para>
    /// </remarks>
    /// <value>默认值为本地 MongoDB 实例：mongodb://127.0.0.1:27017/gameserver?authSource=admin / Default value is local MongoDB instance: mongodb://127.0.0.1:27017/gameserver?authSource=admin</value>
    public string MongoDbDatabaseUrl { get; set; } = "mongodb://127.0.0.1:27017/gameserver?authSource=admin";

    /// <summary>
    /// mongodb 创建的上限集合的最大总大小（MB） / Maximum total size (MB) of capped collection created by MongoDB
    /// </summary>
    public int MongoDbCappedMaxSizeMb { get; set; } = 50;

    /// <summary>
    /// mongodb 创建的上限集合的最大文档数。 / Maximum number of documents in capped collection created by MongoDB.
    /// </summary>
    public int MongoDbCappedMaxDocuments { get; set; } = 50000;

    /// <summary>
    /// 日志存储路径，为 应用程序运行目录下的子目录/logs。 / Log storage path, a subdirectory under the application running directory /logs.
    /// </summary>
    /// <remarks>
    /// 日志文件的存储位置，是绝对路径。 / The storage location of log files, is an absolute path.
    /// </remarks>
    public string LogSavePath { get; set; }

    /// <summary>
    /// 日志文件名，为空时使用默认名称。 / Log file name, uses default name when empty.
    /// </summary>
    public string LogFileName { get; set; } = string.Empty;

    /// <summary>
    /// 是否输出到控制台，默认为 true。 / Whether to output to console, default is true.
    /// </summary>
    /// <remarks>
    /// 控制日志是否同时在控制台显示，便于开发调试。 / Controls whether logs are also displayed in the console for development debugging.
    /// </remarks>
    public bool IsConsole { get; set; } = true;

    /// <summary>
    /// 是否输出到 GrafanaLoki，默认为 false。 / Whether to output to GrafanaLoki, default is false.
    /// </summary>
    public bool IsGrafanaLoki { get; set; } = false;

    /// <summary>
    /// GrafanaLoki 服务地址，默认为 http://localhost:3100。 / GrafanaLoki service address, default is http://localhost:3100.
    /// </summary>
    public string GrafanaLokiUrl { get; set; } = "http://localhost:3100";

    /// <summary>
    /// GrafanaLoki 标签 / GrafanaLoki labels
    /// </summary>
    public Dictionary<string, string> GrafanaLokiLabels { get; set; } = new();

    /// <summary>
    /// GrafanaLoki 其他属性 / GrafanaLoki additional properties
    /// </summary>
    public Dictionary<string, string> GrafanaLokiProperty { get; set; } = new();

    /// <summary>
    /// GrafanaLoki 用户名 / GrafanaLoki username
    /// </summary>
    public string GrafanaLokiUserName { get; set; }

    /// <summary>
    /// GrafanaLoki 密码 / GrafanaLoki password
    /// </summary>
    public string GrafanaLokiPassword { get; set; }

    /// <summary>
    /// 是否启用 GrafanaLoki 数据压缩，默认为 true / Whether to enable GrafanaLoki data compression, default is true
    /// </summary>
    /// <remarks>
    /// 启用压缩可以减少网络传输的数据量，提高传输效率 / Enabling compression can reduce the amount of data transferred over the network and improve transmission efficiency
    /// </remarks>
    public bool GrafanaLokiCompressionEnabled { get; set; } = true;

    /// <summary>
    /// 日志滚动间隔，默认为每天（Day）。 / Log rolling interval, default is per day (Day).
    /// </summary>
    /// <remarks>
    /// 决定日志文件创建新文件的时间间隔，可以是小时、天、月等。 / Determines the time interval for creating new log files, can be hour, day, month, etc.
    /// </remarks>
    public RollingInterval RollingInterval { get; set; } = RollingInterval.Day;

    /// <summary>
    /// 日志输出级别，默认为 Debug。 / Log output level, default is Debug.
    /// </summary>
    /// <remarks>
    /// 控制日志输出的最低级别，低于此级别的日志将不会被记录。 / Controls the minimum level of log output, logs below this level will not be recorded.
    /// </remarks>
    public LogEventLevel LogEventLevel { get; set; } = LogEventLevel.Debug;

    /// <summary>
    /// 是否限制单个文件大小，默认为 true。 / Whether to limit individual file size, default is true.
    /// </summary>
    /// <remarks>
    /// 启用此选项可以防止单个日志文件过大。 / Enabling this option can prevent individual log files from becoming too large.
    /// </remarks>
    public bool IsFileSizeLimit { get; set; } = true;

    /// <summary>
    /// 日志单个文件大小限制，默认为 100MB。 / Log single file size limit, default is 100MB.
    /// 当 IsFileSizeLimit 为 true 时有效。 / Effective when IsFileSizeLimit is true.
    /// </summary>
    /// <remarks>
    /// 当日志文件达到此大小限制时，将创建新的日志文件继续写入。 / When the log file reaches this size limit, a new log file will be created to continue writing.
    /// </remarks>
    public int FileSizeLimitBytes { get; set; } = 100 * 1024 * 1024;

    /// <summary>
    /// 日志文件保留数量限制 默认为 31 个文件,即 31 天的日志文件 / Log file retention count limit, default is 31 files, i.e., 31 days of log files
    /// 当 设置值为 null 时不限制文件数量 / When set to null, no file count limit
    /// </summary>
    /// <remarks>
    /// 用于控制历史日志文件的数量，防止占用过多磁盘空间。 / Used to control the number of historical log files to prevent excessive disk space usage.
    /// </remarks>
    public int? RetainedFileCountLimit { get; set; } = 31;

    /// <summary>
    /// 返回日志配置对象的 JSON 字符串表示形式。
    /// </summary>
    /// <returns>JSON 字符串表示形式 / JSON string representation</returns>
    /// <remarks>
    /// 将当前配置对象序列化为JSON格式，便于配置的存储和传输。 / Serializes the current configuration object to JSON format for easy storage and transmission of configuration.
    /// </remarks>
    public override string ToString()
    {
        return JsonHelper.SerializeFormat(this);
    }
}